import os
os.system("cls")
input("here are 3 things to do after this video:")
input("1)               make a mini program using print and input")
os.system("cls")
input("-    if you don't have ideas..")
os.system("cls")
input("-    if you don't have ideas..Improvise.")
input("or..")
input("there is another way..")
input("I've made you a list of Ideas for you in the description 👇")
os.system("cls")
input("and now..")
os.system("cls")
input("and now..step number2 is..")
input("2)               remake this program")
input("     if you can..😏\n")
os.system("cls")
input("yes..")
os.system("cls")
input("yes..i am talking to you from a python program right now.")
input("if you make this program with every single detail in it...")
input("you are an absolute chad.")
input("note: the program is on github..link in description.")
os.system("cls")
input("finally..the 3rd and last step is..")
input("3)               subscribe for more juice 🥳")

